version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: infrastructure/deployment/dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
    volumes:
      - ../../:/app
      - ai_model_cache:/root/.cache/torch
    depends_on:
      - db
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aiqleads
      - POSTGRES_PASSWORD=aiqleads_secret
      - POSTGRES_DB=aiqleads
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../../infrastructure/monitoring/prometheus_config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ../../infrastructure/monitoring/grafana_dashboard.json:/etc/grafana/provisioning/dashboards/aiqleads.json
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  ai_model_cache:
