name: CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v3
    
    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Step 3: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Step 4: Build and push Docker images
    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          yourlocalJay/aiqleads:latest
          yourlocalJay/aiqleads:${{ github.sha }}
        cache-from: type=registry,ref=yourlocalJay/aiqleads:latest
        cache-to: type=inline
    
    # Step 5: Deploy to production on tagged commits
    - name: Deploy to production
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Deploying version ${{ github.ref_name }} to production"
        # Add deployment scripts here
