name: Docaider Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/services/docaider/**'
      - 'tests/services/test_docaider.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/services/docaider/**'
      - 'tests/services/test_docaider.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7.2
        ports:
          - 6379:6379
    
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/services/requirements.txt
    
    - name: Run Docaider Tests
      env:
        REDIS_URL: redis://localhost:6379/0
      run: |
        pytest tests/services/test_docaider.py -v \
          --cov=src/services/docaider \
          --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
