name: File Operations

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  file-ops:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests