name: File Operations

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to update'
        required: true
      commit_message:
        description: 'Commit message'
        required: true
      branch:
        description: 'Target branch'
        required: true
        default: 'main'
      content:
        description: 'File content'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests
          
      - name: Update file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_PATH: ${{ github.event.inputs.file_path }}
          COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
          FILE_CONTENT: ${{ github.event.inputs.content }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: python .github/scripts/update_files.py