name: Project Automation

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - ready_for_review
      - review_requested

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            
            // Get project details
            const project = await github.rest.projects.listForRepo({
              owner,
              repo,
              state: 'open'
            });
            
            const projectId = project.data.find(p => p.name === 'AIQLeads MVP Development').id;
            
            let newStatus;
            let commitType;
            let llmUsed = 'Claude 3.5 Sonnet';  // Default LLM
            
            if (pr.merged) {
              newStatus = 'Committed';
              commitType = pr.labels.find(l => l.name.startsWith('type:'))?.name || 'New Feature';
            } else if (pr.state === 'closed' && !pr.merged) {
              newStatus = 'To-Do';
            } else if (pr.draft) {
              newStatus = 'Generated';
            } else if (pr.state === 'open' && !pr.draft) {
              newStatus = 'Reviewed';
            }
            
            try {
              // Update status fields
              await github.graphql(`
                mutation($input: UpdateProjectCardInput!) {
                  updateProjectCard(input: $input) {
                    projectCard {
                      id
                    }
                  }
                }
              `, {
                input: {
                  projectId,
                  note: JSON.stringify({
                    status: newStatus,
                    commitType: commitType,
                    llmUsed: llmUsed,
                    lastUpdated: new Date().toISOString()
                  })
                }
              });
              
              console.log(`Updated project card for PR #${pr.number} to status: ${newStatus}`);
              
            } catch (error) {
              console.error('Error updating project:', error);
            }